import type { SupportedLocaleCode } from "@/config/locales";

export type ReservationCopy = {
  reserve: string; title: string; intro: string; date: string; time: string;
  partySize: string; name: string; phone: string; email: string; notes: string;
  optional: string; acceptPolicy: string; submit: string; loading: string;
  noSlots: string; closed: string; disabled: string; outOfRange: string;
  full: string; temporaryError: string; success: string; locator: string;
  pending: string; confirmed: string; backToMenu: string; largeGroup: string;
  selectTime: string;
};

const es: ReservationCopy = {
  reserve:"Reservar",title:"Reserva tu mesa",intro:"Selecciona una fecha y una hora disponible.",date:"Fecha",time:"Hora",partySize:"Personas",name:"Nombre",phone:"Teléfono",email:"Correo electrónico",notes:"Observaciones",optional:"Opcional",acceptPolicy:"Acepto la política y condiciones de reserva",submit:"Solicitar reserva",loading:"Consultando disponibilidad…",noSlots:"No hay horas disponibles.",closed:"El restaurante está cerrado ese día.",disabled:"Las reservas online no están disponibles.",outOfRange:"La fecha está fuera del periodo permitido.",full:"La capacidad está agotada para esta selección.",temporaryError:"Error temporal. Inténtalo de nuevo.",success:"Reserva enviada correctamente",locator:"Localizador",pending:"Pendiente de confirmación",confirmed:"Confirmada",backToMenu:"Volver a la carta",largeGroup:"Para grupos grandes, contacta con el restaurante.",selectTime:"Selecciona una hora",
};
const copies: Record<SupportedLocaleCode, ReservationCopy> = {
  es,
  ca:{reserve:"Reservar",title:"Reserva la teva taula",intro:"Selecciona una data i una hora disponible.",date:"Data",time:"Hora",partySize:"Persones",name:"Nom",phone:"Telèfon",email:"Correu electrònic",notes:"Observacions",optional:"Opcional",acceptPolicy:"Accepto la política i les condicions de reserva",submit:"Sol·licitar reserva",loading:"Consultant disponibilitat…",noSlots:"No hi ha hores disponibles.",closed:"El restaurant està tancat aquest dia.",disabled:"Les reserves en línia no estan disponibles.",outOfRange:"La data és fora del període permès.",full:"La capacitat està exhaurida per a aquesta selecció.",temporaryError:"Error temporal. Torna-ho a provar.",success:"Reserva enviada correctament",locator:"Localitzador",pending:"Pendent de confirmació",confirmed:"Confirmada",backToMenu:"Tornar a la carta",largeGroup:"Per a grups grans, contacta amb el restaurant.",selectTime:"Selecciona una hora"},
  en:{reserve:"Book",title:"Book your table",intro:"Select an available date and time.",date:"Date",time:"Time",partySize:"Guests",name:"Name",phone:"Phone",email:"Email",notes:"Notes",optional:"Optional",acceptPolicy:"I accept the booking policy and conditions",submit:"Request booking",loading:"Checking availability…",noSlots:"No times are available.",closed:"The restaurant is closed that day.",disabled:"Online bookings are unavailable.",outOfRange:"The date is outside the allowed period.",full:"Capacity is full for this selection.",temporaryError:"Temporary error. Please try again.",success:"Booking submitted successfully",locator:"Reference",pending:"Pending confirmation",confirmed:"Confirmed",backToMenu:"Back to menu",largeGroup:"For large groups, contact the restaurant.",selectTime:"Select a time"},
  ro:{reserve:"Rezervă",title:"Rezervă masa",intro:"Alege o dată și o oră disponibile.",date:"Data",time:"Ora",partySize:"Persoane",name:"Nume",phone:"Telefon",email:"E-mail",notes:"Observații",optional:"Opțional",acceptPolicy:"Accept politica și condițiile rezervării",submit:"Trimite rezervarea",loading:"Se verifică disponibilitatea…",noSlots:"Nu există ore disponibile.",closed:"Restaurantul este închis în acea zi.",disabled:"Rezervările online nu sunt disponibile.",outOfRange:"Data este în afara perioadei permise.",full:"Capacitatea este epuizată.",temporaryError:"Eroare temporară. Încearcă din nou.",success:"Rezervare trimisă cu succes",locator:"Cod rezervare",pending:"În așteptarea confirmării",confirmed:"Confirmată",backToMenu:"Înapoi la meniu",largeGroup:"Pentru grupuri mari, contactează restaurantul.",selectTime:"Alege o oră"},
  fr:{reserve:"Réserver",title:"Réservez votre table",intro:"Choisissez une date et une heure disponibles.",date:"Date",time:"Heure",partySize:"Personnes",name:"Nom",phone:"Téléphone",email:"E-mail",notes:"Observations",optional:"Facultatif",acceptPolicy:"J’accepte la politique et les conditions de réservation",submit:"Demander une réservation",loading:"Vérification des disponibilités…",noSlots:"Aucune heure disponible.",closed:"Le restaurant est fermé ce jour-là.",disabled:"Les réservations en ligne sont indisponibles.",outOfRange:"La date est hors de la période autorisée.",full:"La capacité est complète.",temporaryError:"Erreur temporaire. Réessayez.",success:"Réservation envoyée",locator:"Référence",pending:"En attente de confirmation",confirmed:"Confirmée",backToMenu:"Retour à la carte",largeGroup:"Pour les grands groupes, contactez le restaurant.",selectTime:"Choisissez une heure"},
  de:{reserve:"Reservieren",title:"Tisch reservieren",intro:"Wählen Sie ein verfügbares Datum und eine Uhrzeit.",date:"Datum",time:"Uhrzeit",partySize:"Personen",name:"Name",phone:"Telefon",email:"E-Mail",notes:"Anmerkungen",optional:"Optional",acceptPolicy:"Ich akzeptiere die Reservierungsbedingungen",submit:"Reservierung anfragen",loading:"Verfügbarkeit wird geprüft…",noSlots:"Keine Zeiten verfügbar.",closed:"Das Restaurant ist an diesem Tag geschlossen.",disabled:"Online-Reservierungen sind nicht verfügbar.",outOfRange:"Das Datum liegt außerhalb des zulässigen Zeitraums.",full:"Die Kapazität ist ausgeschöpft.",temporaryError:"Vorübergehender Fehler. Erneut versuchen.",success:"Reservierung erfolgreich gesendet",locator:"Buchungscode",pending:"Bestätigung ausstehend",confirmed:"Bestätigt",backToMenu:"Zurück zur Speisekarte",largeGroup:"Für große Gruppen kontaktieren Sie das Restaurant.",selectTime:"Uhrzeit wählen"},
  nl:{reserve:"Reserveren",title:"Reserveer je tafel",intro:"Kies een beschikbare datum en tijd.",date:"Datum",time:"Tijd",partySize:"Personen",name:"Naam",phone:"Telefoon",email:"E-mail",notes:"Opmerkingen",optional:"Optioneel",acceptPolicy:"Ik accepteer het reserveringsbeleid en de voorwaarden",submit:"Reservering aanvragen",loading:"Beschikbaarheid controleren…",noSlots:"Er zijn geen tijden beschikbaar.",closed:"Het restaurant is die dag gesloten.",disabled:"Online reserveren is niet beschikbaar.",outOfRange:"De datum valt buiten de toegestane periode.",full:"De capaciteit is vol.",temporaryError:"Tijdelijke fout. Probeer opnieuw.",success:"Reservering succesvol verzonden",locator:"Reserveringscode",pending:"Wacht op bevestiging",confirmed:"Bevestigd",backToMenu:"Terug naar menu",largeGroup:"Neem voor grote groepen contact op.",selectTime:"Kies een tijd"},
  eu:{reserve:"Erreserbatu",title:"Erreserbatu mahaia",intro:"Aukeratu erabilgarri dagoen data eta ordua.",date:"Data",time:"Ordua",partySize:"Pertsonak",name:"Izena",phone:"Telefonoa",email:"Posta elektronikoa",notes:"Oharrak",optional:"Aukerakoa",acceptPolicy:"Erreserba-politika eta baldintzak onartzen ditut",submit:"Erreserba eskatu",loading:"Erabilgarritasuna egiaztatzen…",noSlots:"Ez dago ordurik erabilgarri.",closed:"Jatetxea itxita dago egun horretan.",disabled:"Online erreserbak ez daude erabilgarri.",outOfRange:"Data baimendutako epetik kanpo dago.",full:"Edukiera beteta dago.",temporaryError:"Aldi baterako errorea. Saiatu berriro.",success:"Erreserba behar bezala bidali da",locator:"Erreferentzia",pending:"Berrespenaren zain",confirmed:"Berretsita",backToMenu:"Kartara itzuli",largeGroup:"Talde handietarako, jarri jatetxearekin harremanetan.",selectTime:"Aukeratu ordua"},
  it:{reserve:"Prenota",title:"Prenota il tuo tavolo",intro:"Seleziona una data e un orario disponibili.",date:"Data",time:"Ora",partySize:"Persone",name:"Nome",phone:"Telefono",email:"E-mail",notes:"Note",optional:"Facoltativo",acceptPolicy:"Accetto la politica e le condizioni di prenotazione",submit:"Richiedi prenotazione",loading:"Verifica disponibilità…",noSlots:"Nessun orario disponibile.",closed:"Il ristorante è chiuso quel giorno.",disabled:"Le prenotazioni online non sono disponibili.",outOfRange:"La data è fuori dal periodo consentito.",full:"La capacità è esaurita.",temporaryError:"Errore temporaneo. Riprova.",success:"Prenotazione inviata correttamente",locator:"Codice prenotazione",pending:"In attesa di conferma",confirmed:"Confermata",backToMenu:"Torna al menu",largeGroup:"Per gruppi numerosi, contatta il ristorante.",selectTime:"Seleziona un orario"},
};

export function getReservationCopy(locale: string) {
  return copies[locale as SupportedLocaleCode] ?? es;
}

const offlinePaymentNotices: Record<SupportedLocaleCode, string> = {
  es: "Tu solicitud de reserva ha sido registrada. El restaurante confirmará la reserva y, si corresponde, te informará sobre el adelanto.",
  ca: "La teva sol·licitud de reserva ha estat registrada. El restaurant confirmarà la reserva i, si correspon, t'informarà sobre l'avançament.",
  en: "Your booking request has been registered. The restaurant will confirm it and, if applicable, inform you about the deposit.",
  ro: "Cererea ta de rezervare a fost înregistrată. Restaurantul o va confirma și, dacă este cazul, te va informa despre avans.",
  fr: "Votre demande de réservation a été enregistrée. Le restaurant la confirmera et vous informera, le cas échéant, de l'acompte.",
  de: "Ihre Reservierungsanfrage wurde registriert. Das Restaurant bestätigt sie und informiert Sie gegebenenfalls über die Anzahlung.",
  nl: "Je reserveringsaanvraag is geregistreerd. Het restaurant bevestigt deze en informeert je indien nodig over de aanbetaling.",
  eu: "Zure erreserba-eskaera erregistratu da. Jatetxeak baieztatuko du eta, hala badagokio, aurrerakinari buruzko informazioa emango dizu.",
  it: "La tua richiesta di prenotazione è stata registrata. Il ristorante la confermerà e, se necessario, ti informerà sull'anticipo.",
};

export function getOfflinePaymentNotice(locale: string) {
  return (
    offlinePaymentNotices[locale as SupportedLocaleCode] ??
    offlinePaymentNotices.es
  );
}
